### ISSUE TITLE
Leaving highlightjs org

### ISSUE THREAD

**Issue by vancluever** [highlightjs/highlightjs-sentinel#3]
Hey folks,

I am no longer with HashiCorp - I also had not been working on Sentinel for quite some time.

I'm removing myself from the organization but I thought I'd just drop a line to let yall know just in case you wanted to contact HashiCorp to get someone else to take over the project or just archive it.

Cheers!

**Comment by joshgoebel** [comment]
Would you have any clue who I might speak to on the Sentinel team?  I hate to just start on the outside with a sales email address with a large company... Or if you know anyone I could just ping here on Github, even better...

**Comment by vancluever** [comment]
@cam-stitt @glennsarti would you be able to tell @joshgoebel if there's any interest in keeping this maintained?

**Comment by cam-stitt** [comment]
Hi @joshgoebel, I'd be happy to help on behalf of the Sentinel team.

**Comment by joshgoebel** [comment]
Added you as a maintainer!
